variable "bucket_name" {
  type        = string
  description = "Bucket name (optional, autogenerated if null)"
  default     = null
}

variable "server_to_client_prefix" {
  type        = string
  description = "The key prefix for TS -> Beacon"
  default     = "s2c"
}

variable "client_to_server_prefix" {
  type        = string
  description = "The key prefix for Beacon -> TS"
  default     = "c2s"
}

variable "aws_region" {
  type        = string
  description = "AWS Region"
  default     = "eu-central-1"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }

  required_version = ">= 1.2"
}

provider "aws" {
  region = var.aws_region
}

resource "random_uuid" "bucket_name" {}

locals {
  bucket_name = coalesce(var.bucket_name, random_uuid.bucket_name.result)
}

# Bucket to forward the UDC2 frames

resource "aws_s3_bucket" "udc2" {
  bucket = local.bucket_name

}

resource "aws_s3_bucket_lifecycle_configuration" "ttl" {
  bucket = aws_s3_bucket.udc2.id

  rule {
    id = "ttl"
    expiration {
      days = 2
    }
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "bucket_acl" {
  bucket = aws_s3_bucket.udc2.id

  block_public_acls       = true  # fine, we’re using policies
  ignore_public_acls      = true  # ignore object ACLs
  block_public_policy     = false # allow public bucket policies
  restrict_public_buckets = false # allow this bucket to be public via policy
}

resource "aws_s3_bucket_policy" "public_subkey_read" {
  bucket = aws_s3_bucket.udc2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowPublicReadUnderSubkey"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:GetObject"
        Resource  = "${aws_s3_bucket.udc2.arn}/${var.server_to_client_prefix}/*"
      }
    ]
  })

  depends_on = [
    aws_s3_bucket_public_access_block.bucket_acl
  ]
}

# Upload notifacation

resource "aws_sqs_queue" "s3_events" {
  name                      = "udc2-${aws_s3_bucket.udc2.id}-${var.client_to_server_prefix}-notification"
  message_retention_seconds = 172800 # 2 days
}

data "aws_iam_policy_document" "s3_to_sqs" {
  statement {
    sid    = "AllowS3SendMessage"
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }

    actions = [
      "sqs:SendMessage",
      "sqs:GetQueueAttributes",
      "sqs:GetQueueUrl",
    ]

    resources = [
      aws_sqs_queue.s3_events.arn,
    ]

    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [aws_s3_bucket.udc2.arn]
    }
  }
}

resource "aws_sqs_queue_policy" "s3_events" {
  queue_url = aws_sqs_queue.s3_events.id
  policy    = data.aws_iam_policy_document.s3_to_sqs.json
}

resource "aws_s3_bucket_notification" "s3_to_sqs" {
  bucket = aws_s3_bucket.udc2.id

  queue {
    id            = "s2c-puts"
    queue_arn     = aws_sqs_queue.s3_events.arn
    events        = ["s3:ObjectCreated:*"]
    filter_prefix = "${var.client_to_server_prefix}/"
  }

  depends_on = [
    aws_sqs_queue_policy.s3_events
  ]
}

# IAM User for the relay

resource "aws_iam_user" "relay_user" {
  name = "udc2-${aws_s3_bucket.udc2.id}-relay"
}

resource "aws_iam_access_key" "relay_user_key" {
  user = aws_iam_user.relay_user.name
}

data "aws_iam_policy_document" "relay_user_policy" {
  statement {
    sid    = "AllowBucketAccess"
    effect = "Allow"

    actions = [
      "s3:ListBucket",
    ]

    resources = [
      aws_s3_bucket.udc2.arn,
    ]
  }

  statement {
    sid    = "AllowObjectAccess"
    effect = "Allow"

    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:DeleteObject",
    ]

    resources = [
      "${aws_s3_bucket.udc2.arn}/*",
    ]
  }

  statement {
    sid    = "AllowReceiveS3EventQueueMessages"
    effect = "Allow"

    actions = [
      "sqs:ReceiveMessage",
      "sqs:DeleteMessage",
      "sqs:GetQueueAttributes",
      "sqs:GetQueueUrl",
      "sqs:ChangeMessageVisibility",
      "sqs:ChangeMessageVisibilityBatch",
      "sqs:DeleteMessageBatch",
    ]

    resources = [
      aws_sqs_queue.s3_events.arn
    ]
  }
}

resource "aws_iam_user_policy" "relay_user_inline" {
  name   = "udc2-${aws_s3_bucket.udc2.id}-relay-access"
  user   = aws_iam_user.relay_user.name
  policy = data.aws_iam_policy_document.relay_user_policy.json
}

# Write only IAM user

resource "aws_iam_user" "write_only_user" {
  name = "udc2-${aws_s3_bucket.udc2.id}-wo"
}

resource "aws_iam_access_key" "write_only_user_key" {
  user = aws_iam_user.write_only_user.name
}

data "aws_iam_policy_document" "write_only_user_policy" {
  statement {
    sid    = "PutObjectUnder"
    effect = "Allow"

    actions = [
      "s3:PutObject",
    ]

    resources = [
      "${aws_s3_bucket.udc2.arn}/${var.client_to_server_prefix}/*",
    ]
  }
}

resource "aws_iam_user_policy" "write_only_user_inline" {
  name   = "udc2-${aws_s3_bucket.udc2.id}-write-only-access"
  user   = aws_iam_user.write_only_user.name
  policy = data.aws_iam_policy_document.write_only_user_policy.json
}

# Output

output "bucket_name" {
  value = aws_s3_bucket.udc2.id
}

output "relay_user_access_key_id" {
  value = aws_iam_access_key.relay_user_key.id
}

output "relay_user_secret_access_key" {
  value     = aws_iam_access_key.relay_user_key.secret
  sensitive = true
}

output "write_only_user_access_key_id" {
  value = aws_iam_access_key.write_only_user_key.id
}

output "write_only_user_secret_access_key" {
  value     = aws_iam_access_key.write_only_user_key.secret
  sensitive = true
}

output "server_to_client_prefix" {
  value = var.server_to_client_prefix
}

output "client_to_server_prefix" {
  value = var.client_to_server_prefix
}

output "s3_events_queue" {
  value = aws_sqs_queue.s3_events.id
}

output "aws_region" {
  value = var.aws_region
}
